# GitHub repository information
owner: Loftwah # Your GitHub username
repo: linkarooie-upptime # Your new repository name

# List of endpoints to monitor
sites:
  - name: Linkarooie
    url: https://linkarooie.com

# Optionally assign GitHub users to downtime issues
assignees: 
  - Loftwah # You can assign issues to yourself or team members

# Status website configuration
status-website:
  # If you're using a custom domain (like status.linkarooie.com), add it here
  cname: status.linkarooie.com
  # If you're not using a custom domain, uncomment the line below and add your repo name
  # baseUrl: /linkarooie-upptime 
  logoUrl: https://linkarooie.com/favicon.ico # Update with your logo if available
  name: Linkarooie Status # Status website title
  introTitle: "Linkarooie Status"
  introMessage: "This page shows **real-time** uptime data for Linkarooie. Powered by [GitHub Actions](https://github.com/features/actions) and [Upptime](https://github.com/upptime/upptime)."

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Loftwah/linkarooie-upptime

# Optional notifications (e.g., Slack, Discord)
notifications:
  slack: false
  discord: false
